import time
# These are the names generated by Bazel for your targets
from protos import simple_proto_pb2
# Note: Bazel generates xla_data_pb2 in a path matching its repo structure
from xla import xla_data_pb2


def create_simple_proto():
    p = simple_proto_pb2.XLAData()
    return p

if __name__ == "__main__":
    msg = create_simple_proto()
    print("--- Experiment Metadata ---")
    print(msg)